# Generated by Django 4.1.7 on 2023-04-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darbi', '0002_manager_created_at_manager_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='automation',
            field=models.IntegerField(blank=True, null=True, verbose_name='Aut.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Pabeigšanas datums'),
        ),
        migrations.AlterField(
            model_name='project',
            name='concrete_column',
            field=models.IntegerField(blank=True, null=True, verbose_name='Betona stabi'),
        ),
        migrations.AlterField(
            model_name='project',
            name='concrete_foundation',
            field=models.IntegerField(blank=True, null=True, verbose_name='Betona cokoli'),
        ),
        migrations.AlterField(
            model_name='project',
            name='concrete_slab',
            field=models.IntegerField(blank=True, null=True, verbose_name='Betona pasētas'),
        ),
        migrations.AlterField(
            model_name='project',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Nodošanas datums'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Objekta apraksts'),
        ),
        migrations.AlterField(
            model_name='project',
            name='forged_window',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kaltie posmi'),
        ),
        migrations.AlterField(
            model_name='project',
            name='large_gate',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lielie vārti'),
        ),
        migrations.AlterField(
            model_name='project',
            name='mesh_in_roll',
            field=models.IntegerField(blank=True, null=True, verbose_name='Siets ruļļos'),
        ),
        migrations.AlterField(
            model_name='project',
            name='metal_column',
            field=models.IntegerField(blank=True, null=True, verbose_name='Metāla stabi'),
        ),
        migrations.AlterField(
            model_name='project',
            name='panel_3d2d',
            field=models.IntegerField(blank=True, null=True, verbose_name='Paneļi 3D/2D'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sliding_gate',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bīdāmie vārti'),
        ),
        migrations.AlterField(
            model_name='project',
            name='small_gate',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mazie vārti'),
        ),
        migrations.AlterField(
            model_name='project',
            name='wooden_frame',
            field=models.IntegerField(blank=True, null=True, verbose_name='Koka posmi'),
        ),
    ]
