# Generated by Django 4.1.7 on 2023-06-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darbi', '0003_alter_project_automation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='full_payment',
            field=models.BooleanField(default=False, verbose_name='Pilnībā apmaksāts'),
        ),
    ]
