# Generated by Django 4.1.7 on 2023-06-23 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('darbi', '0004_project_full_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='advance_payment',
        ),
    ]
